### ISSUE TITLE
custom clang_format style

### ISSUE THREAD

**Issue by cathaysia** [KDAB/clang-format-rs#6]
It would be great if could add custom strings

```rust
#[derive(Debug, PartialEq)]
pub enum ClangFormatStyle {
    Chromium,
    Default,
    File,
    Google,
    Llvm,
    Mozilla,
    WebKit,
   Custom(String)
}
```

**Comment by ahayzen-kdab** [comment]
Thanks for reporting this issue.

This sounds like a good idea, can you describe what the custom string may contain ? and what that looks like when you call it on the command line ?

As note at the moment `ClangFormatStyle` is used for the value in the command line argument `--style={}`.

**Comment by cathaysia** [comment]
Guess we have a .clang_format like this:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
AlignAfterOpenBracket: BlockIndent
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: None
AllowShortLoopsOnASingleLine: false
```

then we can pass this on cmdline:

```console
clang-format --style="{ BasedOnStyle: Google, IndentWidth: 4, AlignAfterOpenBracket: BlockIndent, AllowShortBlocksOnASingleLine: Never, AllowShortCaseLabelsOnASingleLine: false, AllowShortEnumsOnASingleLine: false, AllowShortFunctionsOnASingleLine: None, AllowShortIfStatementsOnASingleLine: Never, AllowShortLambdasOnASingleLine: None, AllowShortLoopsOnASingleLine: false }"
```
